apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-cliente-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbsilmann/gitops-argocd.git
    targetRevision: HEAD
    path: cliente_2/apps/tomcat
  destination:
    server: https://kubernetes.default.svc
    namespace: cliente-2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
